[WIP] Migrate from callbacks to async/await
slidoapp/oauth2-swift pull request #21
Opened 2024-11-28 15:20 UTC by DominikPalo

https://sli-do.atlassian.net/browse/PS-22018

2024-11-29 14:35 UTC, jozefizso commented on Sources/DataLoader/OAuth2DataLoader.swift
> +		return authParams
This looks like a great candidate for read/write lock mechanism to correctly synchronize multithreaded access.

2025-05-19 10:49 UTC, m-kovac approved these changes

2025-05-20 14:20 UTC, jozefizso requested changes

2025-05-20 14:20 UTC, jozefizso commented on README.md
> +OAuth2 requires Xcode 12.4, the built framework can be used on **OS X 10.15**, **iOS 13**, **tvOS** 13, **watchOS 6** and later.
```suggestion
OAuth2 requires Xcode 12.4, the built framework can be used on **OS X 10.15**, **iOS 13**, **tvOS 13**, **watchOS 6** and later.
```

2025-06-11 11:30 UTC, jozefizso approved these changes

2025-06-11 11:45 UTC, filipbodor approved these changes

2025-06-12 06:15 UTC, m-kovac approved these changes

2025-06-12 07:10 UTC, merged