feat: implement resource aware authorization
slidoapp/oauth2-swift pull request #9
Opened 2023-11-23 12:10 UTC by tomondre

Issue: PS-19496

2023-11-23 14:36 UTC, jozefizso commented on Tests/FlowTests/OAuth2ExchangeAccessTokenForResourceTests.swift
> +//  Copyright 2023 Dominik Paľo
The correct copyright is Cisco Systems:


```suggestion
//  Copyright 2023 Cisco Systems, Inc. All rights reserved.
```

2023-11-24 08:53 UTC, tomondre commented on Tests/FlowTests/OAuth2ExchangeAccessTokenForResourceTests.swift
> +//  Copyright 2023 Dominik Paľo
Added 😄. I got a reference from `OAuth2DeviceGrantTests.swift`, which also has the `Copyright 2023 Dominik Paľo` signature. Should I also change this? @DominikPalo

2023-11-24 13:29 UTC, DominikPalo requested changes

2023-11-24 13:29 UTC, DominikPalo commented on Sources/Flows/OAuth2.swift
> +        req.params["resource"] = resourceUrl.absoluteString + "/" + resourceType + "/" + resourceId
It is always safer to use methods provided by URL struct to manipulate URLs:
```suggestion
        		req.params["resource"] = resourceUrl
				.appendingPathComponent(resourceType)
				.appendingPathComponent(resourceId)
				.absoluteString
```

2023-11-24 13:29 UTC, DominikPalo commented on Sources/Flows/OAuth2.swift
Please, use tabs for indentation (the file contains mixed spaces and tabs)

2023-11-24 13:29 UTC, DominikPalo commented on Sources/Flows/OAuth2.swift
> +        let req = OAuth2AuthRequest(url: (clientConfig.tokenURL ?? clientConfig.authorizeURL))
Code-style consistency: missing empty line
```suggestion
        }
 
        let req = OAuth2AuthRequest(url: (clientConfig.tokenURL ?? clientConfig.authorizeURL))
```

2023-11-24 13:29 UTC, DominikPalo commented on Sources/Flows/OAuth2.swift
> +        req.params["scope"] = clientConfig.scope
Please, order fields according to the [RFC8693, section 2.1](https://datatracker.ietf.org/doc/html/rfc8693#section-2.1). Also, the `client_id` param is not in that RFC, so please omit it (not sure why the client_id is needed in the request, as it is part of JWT, so it can be extracted on the server side...)

2023-11-24 13:29 UTC, DominikPalo commented on Sources/Flows/OAuth2.swift
> +            self.logger?.debug("OAuth2", msg: "Error exchanging access token for resource \(resourceType.description) with ID \(resourceId): \(error)")
`resourceType` is a string, which is interpolated implicitly
```suggestion
            self.logger?.debug("OAuth2", msg: "Error exchanging access token for resource \(resourceType) with ID \(resourceId): \(error)")
```

2023-11-24 13:29 UTC, DominikPalo commented on Sources/Flows/OAuth2.swift
> +            logger?.debug("OAuth2", msg: "Exchanging access token for resource \(resourceType.description) with ID \(resourceId) from \(post.url?.description ?? "nil")")
`resourceType` is a string, which is interpolated implicitly
```suggestion
            logger?.debug("OAuth2", msg: "Exchanging access token for resource \(resourceType) with ID \(resourceId) from \(post.url?.description ?? "nil")")
```

2023-11-24 13:29 UTC, DominikPalo commented on Sources/Flows/OAuth2.swift
> +            perform(request: post) { response in
Code-style consistency: missing empty line
```suggestion
            logger?.debug("OAuth2", msg: "Exchanging access token for resource \(resourceType.description) with ID \(resourceId) from \(post.url?.description ?? "nil")")

            perform(request: post) { response in
```

2023-11-24 13:29 UTC, DominikPalo commented on Sources/Flows/OAuth2.swift
> +                    callback(nil, err)
Unnecessary constant
```suggestion
                    callback(nil, error.asOAuth2Error)
```

2023-11-24 13:29 UTC, DominikPalo commented on Tests/FlowTests/OAuth2ExchangeAccessTokenForResourceTests.swift
Please, use tabs for identation

2023-11-24 13:47 UTC, tomondre commented on Sources/Flows/OAuth2.swift
> +        req.params["resource"] = resourceUrl.absoluteString + "/" + resourceType + "/" + resourceId
Reflecting back on this change, I think we should avoid the structure `/{resourceType}/{resourceId}`, as in OAuth spec the resource can be in any format.

2023-11-24 14:26 UTC, tomondre commented on Sources/Flows/OAuth2.swift
> +        req.params["scope"] = clientConfig.scope
Good point. I will ask about this in the team. According to Slido's OAuth2 documentation:
> client_id: REQUIRED when subject_token_type: 'urn:ietf:params:oauth:token-type:access_token'

2023-11-24 15:44 UTC, DominikPalo requested changes

2023-11-24 15:44 UTC, DominikPalo commented on Sources/Flows/OAuth2.swift
> +    */
Spaces... 😢

2023-11-24 15:44 UTC, DominikPalo commented on Sources/Flows/OAuth2.swift
> +    */
Spaces... 😢 Also, it describes the `doExchangeRefreshToken`, not the `doExchangeAccessTokenForResource` function

2023-11-24 15:44 UTC, DominikPalo commented on Tests/FlowTests/OAuth2ExchangeAccessTokenForResourceTests.swift
> +        let req = try! oauth.tokenRequestForExchangeAccessTokenForResource(resourcePath: resourcePath).asURLRequest(for: oauth)
Spaces... 😢

2023-11-24 15:44 UTC, DominikPalo commented on Tests/FlowTests/OAuth2ExchangeAccessTokenForResourceTests.swift
> +        try! oauth.doExchangeAccessTokenForResource(resourcePath: resourcePath) { token, error in
Spaces... 😢

2023-11-24 15:44 UTC, DominikPalo commented on Tests/FlowTests/OAuth2ExchangeAccessTokenForResourceTests.swift
> +        try! oauth.doExchangeAccessTokenForResource(resourcePath: resourcePath) { token, error in
Spaces... 😢

2023-11-24 15:44 UTC, DominikPalo commented on Tests/FlowTests/OAuth2ExchangeAccessTokenForResourceTests.swift
> +        let req = try! oauth.tokenRequestForExchangeAccessTokenForResource(resourcePath: resourcePath).asURLRequest(for: oauth)
Spaces... 😢

2023-11-24 15:44 UTC, DominikPalo commented on Tests/FlowTests/OAuth2ExchangeAccessTokenForResourceTests.swift
> +        let req = try! oauth.tokenRequestForExchangeAccessTokenForResource(resourcePath: resourcePath).asURLRequest(for: oauth)
Spaces... 😢

2023-11-24 15:47 UTC, DominikPalo commented on Tests/FlowTests/OAuth2ExchangeAccessTokenForResourceTests.swift
There are still multiple lines indented using spaces

2023-12-19 14:08 UTC, tomondre commented
Would it be possible to approve/comment? 😄

2024-01-10 14:40 UTC, DominikPalo approved these changes

2024-01-10 15:48 UTC, jozefizso approved these changes

2024-01-10 15:51 UTC, merged